INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (1, 'Gold Mine', 150, 0, 0, 3, 3, 1, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (2, 'Gold Mine', 1000, 0, 0, 3, 3, 2, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (3, 'Gold Mine', 4000, 0, 0, 3, 3, 3, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (4, 'Gold Mine', 16000, 0, 0, 3, 3, 4, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (5, 'Gold Mine', 50000, 0, 0, 3, 3, 5, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (6, 'Gold Mine', 100000, 0, 0, 3, 3, 6, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (7, 'Gold Mine', 250000, 0, 0, 3, 3, 7, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (8, 'Gold Mine', 500000, 0, 0, 3, 3, 8, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (9, 'Gold Mine', 1000000, 0, 0, 3, 3, 9, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (10, 'Gold Mine', 2000000, 0, 0, 3, 3, 10, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (11, 'Gold Mine', 3000000, 0, 0, 3, 3, 11, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (12, 'Gold Mine', 4000000, 0, 0, 3, 3, 12, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (13, 'Gold Mine', 5000000, 0, 0, 3, 3, 13, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (14, 'Gold Mine', 6000000, 0, 0, 3, 3, 14, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (15, 'Gold Mine', 7000000, 0, 0, 3, 3, 15, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (16, 'Elixir Collector', 0, 150, 0, 3, 3, 1, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (17, 'Elixir Collector', 0, 1000, 0, 3, 3, 2, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (18, 'Elixir Collector', 0, 4000, 0, 3, 3, 3, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (19, 'Elixir Collector', 0, 16000, 0, 3, 3, 4, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (20, 'Elixir Collector', 0, 50000, 0, 3, 3, 5, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (21, 'Elixir Collector', 0, 100000, 0, 3, 3, 6, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (22, 'Elixir Collector', 0, 250000, 0, 3, 3, 7, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (23, 'Elixir Collector', 0, 500000, 0, 3, 3, 8, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (24, 'Elixir Collector', 0, 1000000, 0, 3, 3, 9, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (25, 'Elixir Collector', 0, 2000000, 0, 3, 3, 10, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (26, 'Elixir Collector', 0, 3000000, 0, 3, 3, 11, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (27, 'Elixir Collector', 0, 4000000, 0, 3, 3, 12, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (28, 'Elixir Collector', 0, 5000000, 0, 3, 3, 13, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (29, 'Elixir Collector', 0, 6000000, 0, 3, 3, 14, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (30, 'Elixir Collector', 0, 7000000, 0, 3, 3, 15, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (31, 'Dark Elixir Drill', 0, 0, 10000, 3, 3, 1, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (32, 'Dark Elixir Drill', 0, 0, 30000, 3, 3, 2, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (33, 'Dark Elixir Drill', 0, 0, 70000, 3, 3, 3, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (34, 'Dark Elixir Drill', 0, 0, 120000, 3, 3, 4, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (35, 'Dark Elixir Drill', 0, 0, 200000, 3, 3, 5, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (36, 'Dark Elixir Drill', 0, 0, 300000, 3, 3, 6, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (37, 'Dark Elixir Drill', 0, 0, 420000, 3, 3, 7, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (38, 'Dark Elixir Drill', 0, 0, 560000, 3, 3, 8, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (39, 'Dark Elixir Drill', 0, 0, 720000, 3, 3, 9, 'Resource');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (40, 'Cannon', 500, 0, 0, 3, 3, 1, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (41, 'Cannon', 1000, 0, 0, 3, 3, 2, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (42, 'Cannon', 2000, 0, 0, 3, 3, 3, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (43, 'Cannon', 4000, 0, 0, 3, 3, 4, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (44, 'Cannon', 16000, 0, 0, 3, 3, 5, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (45, 'Cannon', 32000, 0, 0, 3, 3, 6, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (46, 'Cannon', 64000, 0, 0, 3, 3, 7, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (47, 'Cannon', 128000, 0, 0, 3, 3, 8, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (48, 'Cannon', 256000, 0, 0, 3, 3, 9, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (49, 'Cannon', 512000, 0, 0, 3, 3, 10, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (50, 'Cannon', 1024000, 0, 0, 3, 3, 11, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (51, 'Cannon', 2048000, 0, 0, 3, 3, 12, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (52, 'Cannon', 4096000, 0, 0, 3, 3, 13, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (53, 'Cannon', 8192000, 0, 0, 3, 3, 14, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (54, 'Cannon', 12288000, 0, 0, 3, 3, 15, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (55, 'Archer Tower', 1000, 0, 0, 3, 3, 1, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (56, 'Archer Tower', 2000, 0, 0, 3, 3, 2, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (57, 'Archer Tower', 4000, 0, 0, 3, 3, 3, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (58, 'Archer Tower', 8000, 0, 0, 3, 3, 4, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (59, 'Archer Tower', 16000, 0, 0, 3, 3, 5, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (60, 'Archer Tower', 32000, 0, 0, 3, 3, 6, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (61, 'Archer Tower', 64000, 0, 0, 3, 3, 7, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (62, 'Archer Tower', 128000, 0, 0, 3, 3, 8, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (63, 'Archer Tower', 256000, 0, 0, 3, 3, 9, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (64, 'Archer Tower', 512000, 0, 0, 3, 3, 10, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (65, 'Archer Tower', 1024000, 0, 0, 3, 3, 11, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (66, 'Archer Tower', 2048000, 0, 0, 3, 3, 12, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (67, 'Archer Tower', 4096000, 0, 0, 3, 3, 13, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (68, 'Archer Tower', 8192000, 0, 0, 3, 3, 14, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (69, 'Archer Tower', 16384000, 0, 0, 3, 3, 15, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (70, 'Wizard Tower', 0, 200000, 0, 3, 3, 1, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (71, 'Wizard Tower', 0, 400000, 0, 3, 3, 2, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (72, 'Wizard Tower', 0, 800000, 0, 3, 3, 3, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (73, 'Wizard Tower', 0, 1200000, 0, 3, 3, 4, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (74, 'Wizard Tower', 0, 1600000, 0, 3, 3, 5, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (75, 'Wizard Tower', 0, 2000000, 0, 3, 3, 6, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (76, 'Wizard Tower', 0, 2400000, 0, 3, 3, 7, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (77, 'Wizard Tower', 0, 2800000, 0, 3, 3, 8, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (78, 'Wizard Tower', 0, 3200000, 0, 3, 3, 9, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (79, 'Wizard Tower', 0, 3600000, 0, 3, 3, 10, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (80, 'Wizard Tower', 0, 4000000, 0, 3, 3, 11, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (81, 'Wizard Tower', 0, 4500000, 0, 3, 3, 12, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (82, 'Wizard Tower', 0, 5000000, 0, 3, 3, 13, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (83, 'Wizard Tower', 0, 5500000, 0, 3, 3, 14, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (84, 'Wall', 200, 0, 0, 1, 1, 1, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (85, 'Wall', 1000, 0, 0, 1, 1, 2, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (86, 'Wall', 5000, 0, 0, 1, 1, 3, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (87, 'Wall', 10000, 0, 0, 1, 1, 4, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (88, 'Wall', 30000, 0, 0, 1, 1, 5, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (89, 'Wall', 50000, 0, 0, 1, 1, 6, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (90, 'Wall', 100000, 0, 0, 1, 1, 7, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (91, 'Wall', 250000, 0, 0, 1, 1, 8, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (92, 'Wall', 500000, 0, 0, 1, 1, 9, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (93, 'Wall', 1000000, 1000000, 0, 1, 1, 10, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (94, 'Wall', 1500000, 1500000, 0, 1, 1, 11, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (95, 'Wall', 2000000, 2000000, 0, 1, 1, 12, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (96, 'Wall', 2500000, 2500000, 0, 1, 1, 13, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (97, 'Wall', 3000000, 3000000, 0, 1, 1, 14, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (98, 'Wall', 3500000, 3500000, 0, 1, 1, 15, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (99, 'Wall', 4000000, 4000000, 0, 1, 1, 16, 'Defensive');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (100, 'Barracks', 200, 0, 0, 3, 3, 1, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (101, 'Barracks', 400, 0, 0, 3, 3, 2, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (102, 'Barracks', 1000, 0, 0, 3, 3, 3, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (103, 'Barracks', 2000, 0, 0, 3, 3, 4, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (104, 'Barracks', 4000, 0, 0, 3, 3, 5, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (105, 'Barracks', 10000, 0, 0, 3, 3, 6, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (106, 'Barracks', 20000, 0, 0, 3, 3, 7, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (107, 'Barracks', 40000, 0, 0, 3, 3, 8, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (108, 'Barracks', 80000, 0, 0, 3, 3, 9, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (109, 'Barracks', 160000, 0, 0, 3, 3, 10, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (110, 'Barracks', 320000, 0, 0, 3, 3, 11, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (111, 'Barracks', 640000, 0, 0, 3, 3, 12, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (112, 'Barracks', 1280000, 0, 0, 3, 3, 13, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (113, 'Barracks', 2560000, 0, 0, 3, 3, 14, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (114, 'Barracks', 5120000, 0, 0, 3, 3, 15, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (115, 'Barracks', 7000000, 0, 0, 3, 3, 16, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (116, 'Dark Barracks', 0, 150000, 0, 3, 3, 1, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (117, 'Dark Barracks', 0, 300000, 0, 3, 3, 2, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (118, 'Dark Barracks', 0, 600000, 0, 3, 3, 3, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (119, 'Dark Barracks', 0, 800000, 0, 3, 3, 4, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (120, 'Dark Barracks', 0, 1000000, 0, 3, 3, 5, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (121, 'Dark Barracks', 0, 2000000, 0, 3, 3, 6, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (122, 'Dark Barracks', 0, 3000000, 0, 3, 3, 7, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (123, 'Dark Barracks', 0, 4000000, 0, 3, 3, 8, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (124, 'Dark Barracks', 0, 5000000, 0, 3, 3, 9, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (125, 'Dark Barracks', 0, 6000000, 0, 3, 3, 10, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (126, 'Laboratory', 0, 75000, 0, 4, 4, 1, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (127, 'Laboratory', 0, 150000, 0, 4, 4, 2, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (128, 'Laboratory', 0, 300000, 0, 4, 4, 3, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (129, 'Laboratory', 0, 600000, 0, 4, 4, 4, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (130, 'Laboratory', 0, 1200000, 0, 4, 4, 5, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (131, 'Laboratory', 0, 2400000, 0, 4, 4, 6, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (132, 'Laboratory', 0, 3600000, 0, 4, 4, 7, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (133, 'Laboratory', 0, 4800000, 0, 4, 4, 8, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (134, 'Laboratory', 0, 6000000, 0, 4, 4, 9, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (135, 'Laboratory', 0, 7200000, 0, 4, 4, 10, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (136, 'Laboratory', 0, 8400000, 0, 4, 4, 11, 'Army');
INSERT INTO Buildings (BuildingID, Name, UpgradeCost_Gold, UpgradeCost_Elixir, UpgradeCost_DarkElixir, Width, Height, Level, Type) VALUES (137, 'Laboratory', 0, 9600000, 0, 4, 4, 12, 'Army');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (1, 'Barbarian', 300, 50, 'GroundToGround', 1, 'Elixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (2, 'Archer', 125, 40, 'GroundToBoth', 1, 'Elixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (3, 'Giant', 2000, 80, 'GroundToGround', 5, 'Elixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (4, 'Minion', 180, 60, 'AirToBoth', 2, 'DarkElixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (5, 'Hog Rider', 800, 200, 'GroundToGround', 5, 'DarkElixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (6, 'Valkyrie', 1200, 180, 'GroundToGround', 8, 'DarkElixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (7, 'Super Barbarian', 1500, 200, 'GroundToGround', 1, 'DarkElixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (8, 'Super Archer', 300, 80, 'GroundToBoth', 1, 'DarkElixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (9, 'Wizard', 130, 150, 'GroundToBoth', 4, 'Elixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (10, 'Golem', 4500, 120, 'GroundToGround', 30, 'DarkElixir');
INSERT INTO Troops (TroopID, Name, HitPoint, Damage, DamageType, Capacity, Resource) VALUES (11, 'Witch', 400, 100, 'GroundToBoth', 12, 'DarkElixir');
